"""initial tables

Revision ID: 828978b09d0c
Revises: 
Create Date: 2026-06-17 14:14:05.154604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '828978b09d0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('joined_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_member_class'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_member_class'), 'classes', ['class_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('joined_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('active', 'inactive', 'archived'), server_default=sa.text("'active'"), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))

    # ### end Alembic commands ###
